[toolchain]
[features]
resolution = true
skip-lint = false





[programs.localnet]
solana_presale = "abKv7EDBx3REPsbgpZVfyn39RH3kBsYUKQy18AfdHf9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"