[toolchain]
[features]
resolution = true
skip-lint = false

[programs.mainnet]
solana_presale = "PwPPdoNVMJiUbQyHLTRif18JdKJiAKopv9y4i78y8M3"

[programs.localnet]
solana_presale = "dseD4adu7DMFkPUkVY6nSWSRePq2gAzftGQZYuAxRbg"

[programs.devnet]
solana_presale = "dseD4adu7DMFkPUkVY6nSWSRePq2gAzftGQZYuAxRbg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solana_presale.ts"
