[toolchain]
[features]
resolution = true
skip-lint = false

[programs.mainnet]
solana_presale = "8BBRV7FzKbi923SVZm3udHB1VTDQwwNnbHyyB114WG5A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"
